In [3]:
import numpy as np
criterias = np.array([
      [0.8,0.7,0.65,0.4,0.2],
      [0.5,0.4,0.4,0.6,0.3],
      [0.6,0.6,0.65,0.5,0.7],
      [0.4,0.3,0.55,0.6,0.6],
      [0.5,0.2,0.45,0.3,0.4]
      ])

criteria_names = ['c1', 'c2', 'c3', 'c4','c5']
relative_importances = {
    ('c1', 'c2'): 2,
    ('c1', 'c3'): 3,
    ('c1', 'c4'): 4,
    ('c1', 'c5'): 5,
    ('c2', 'c3'): 2,
    ('c2', 'c4'): 3,
    ('c2', 'c5'): 4,
    ('c3', 'c4'): 2,
    ('c3', 'c5'): 3,
    ('c4', 'c5'): 2
}

In [4]:
importance_matrix = np.zeros((len(criteria_names), len(criteria_names)))

# Fill in the matrix with relative importances
for i in range(len(criteria_names)):
    for j in range(len(criteria_names)):
        if i == j:
            importance_matrix[i, j] = 1  # Diagonal elements are 1
        elif (criteria_names[i], criteria_names[j]) in relative_importances:
            importance_matrix[i, j] = relative_importances[(criteria_names[i], criteria_names[j])]
        else:
            # Use the reciprocal value if the inverse relationship exists
            importance_matrix[i, j] = 1 / importance_matrix[j, i]

print(importance_matrix)

[[1.         2.         3.         4.         5.        ]
 [0.5        1.         2.         3.         4.        ]
 [0.33333333 0.5        1.         2.         3.        ]
 [0.25       0.33333333 0.5        1.         2.        ]
 [0.2        0.25       0.33333333 0.5        1.        ]]


In [5]:
from numpy.linalg import eig

eig_val, eig_vec = eig(importance_matrix)
eig_max_index = np.argmax(eig_val)
max_eig_vec = eig_vec[:, eig_max_index]

# the required values of coefficient
max_eig_vec *= len(criteria_names)
print(max_eig_vec)

[3.93422842+0.j 2.46763994+0.j 1.50325926+0.j 0.91417426+0.j
 0.58060045+0.j]


In [6]:
eig_vec

array([[ 3.93422842+0.j        , -0.83941118+0.j        ,
        -0.83941118-0.j        , -0.69490202+0.j        ,
        -0.69490202-0.j        ],
       [ 2.46763994+0.j        , -0.14964461-0.39685253j,
        -0.14964461+0.39685253j,  0.46169777-0.30450968j,
         0.46169777+0.30450968j],
       [ 1.50325926+0.j        ,  0.19444122-0.18813114j,
         0.19444122+0.18813114j, -0.05739622+0.36022256j,
        -0.05739622-0.36022256j],
       [ 0.91417426+0.j        ,  0.14981044+0.0560642j ,
         0.14981044-0.0560642j , -0.13333364-0.21378514j,
        -0.13333364+0.21378514j],
       [ 0.58060045+0.j        , -0.00961053+0.12893404j,
        -0.00961053-0.12893404j,  0.1008302 +0.06720803j,
         0.1008302 -0.06720803j]])

In [7]:
new_criterias = []
for i in range(len(criterias)):
  new_criterias.append(criterias[i] ** np.real(max_eig_vec[i]))
new_criterias

[array([0.41565583, 0.24579911, 0.18363625, 0.02719024, 0.00177866]),
 array([0.18078665, 0.10423831, 0.10423831, 0.28350268, 0.0512535 ]),
 array([0.46398486, 0.46398486, 0.52331149, 0.35275556, 0.58498158]),
 array([0.43272649, 0.3326578 , 0.57895692, 0.62689035, 0.62689035]),
 array([0.66868541, 0.39280563, 0.62900635, 0.49706864, 0.58742964])]

In [8]:
#The best alternative:
min_values = np.min(new_criterias, axis=0)
min_max = np.max(min_values)
index = np.argwhere(min_values == min_max).flatten()[0] + 1

print(f"The best alternative is: {{{min_max}/A{index}}}")

The best alternative is: {0.1807866510215972/A1}
